export const FEATURE_LABELS: Record<string, string> = {
  start_x: "Start x",
  start_y: "Start y",
  end_x: "End x",
  end_y: "End y",
  length: "Pass length",
  height: "Pass height",
  angle: "Pass angle",
  duration: "Duration",
  body_part: "Body part",
  under_pressure: "Under pressure",
  log_velocity: "Velocity (log)",
  angle_sin: "Angle (sin)",
  angle_cos: "Angle (cos)",
  start_distance_to_goal: "Start distance to goal",
  end_distance_to_goal: "End distance to goal",
  progressive_distance: "Progressive distance",
  direction_to_goal: "Goal direction",
  direction_to_goal_cos: "Goal direction (cos)",
  duration_x_under_pressure: "Duration × pressure",
  length_x_under_pressure: "Length × pressure",
  log_velocity_x_under_pressure: "Velocity × pressure",
  "(duration+log_velocity)": "Duration + velocity",
  "min(end_x,duration)": "min(End x, Duration)",
  "min(duration,end_y)": "min(Duration, End y)",
  "residual(duration)": "Duration residual",
  "freq(duration)": "Duration frequency",
};
